### PR TITLE
Serverless 3 artillery

### PR DESCRIPTION
**Pull request by Plitzer**
## Reason for change

This is the underlying package for `bom-artillery`, and spins up required infrastructure and load to run a performance test.

There are a number of breaking changes that needed to be addressed to update this to v3. I considered the option of restricting bom-artillery to run in serverless < 3 and install it outside of the project environment, but I managed to get it working with v3 and it's better to uplift it.

Ticket: https://tools.spint.bom.gov.au/jira/browse/DCCED-3841

## Description of Changes

- Lots of minor changes to README/references to the repo this was forked from
- Removed some unnecessary files
- Added Jenkins deployment pipeline
- Renamed package to bom-serverless-artillery instead of `serverless2-artillery` that would need to be named `serverless3-artillery` otherwise...
- Updated serverless files to comply with v3, and upgrade to nodejs16.x
- Rename the service in serverless.yml to `slsart` so bom-artillery doesn't have to
- Fix serverless constructor arguments using output from `resolveCliArgs` (exported from serverless/lib/cli/resolve-input.js)
- Tested with api-warnings (notifications performance and normal performance) and working as expected. Unsure how to run the testing in this project or if it would even be worth it with all the serverless changes to the integration test will have to do for now.

This is a:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change)
- [ ] New or improved tests (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality or implements non-functional requirement)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation or design proposal

## Checklist

- [ ] This PR has a descriptive title
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and docs have been updated.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] This change requires an Akamai change.  Cherwell ticket number is in Reason for Change.
- [ ] This needs a change request.  CR# is in title.

### CODE REVIEW

**Review by MichaelBellBOM — COMMENTED** [review]
This looks good, but how confident are we that this will still work correctly.

@nylemat  Could you look over this to see it makes sense.

**Review by nylemat — COMMENTED** [review]
@Plitzer, first of all, thank you very much for addressing this issue. 

My only thought is to run a couple of rounds of tests before we roll it out. We should make sure that existing cloud formation stack is removed before we run the test or else it would use the old infrastructure

@Plitzer, let me know, I can help you with testing

**Comment by Plitzer** [comment]
> @Plitzer, first of all, thank you very much for addressing this issue.
> 
> My only thought is to run a couple of rounds of tests before we roll it out. We should make sure that existing cloud formation stack is removed before we run the test or else it would use the old infrastructure
> 
> @Plitzer, let me know, I can help you with testing

Thanks @nylemat 
The infrastructure should remain the same, only that the lambda runtime should be running nodejs16.x. I believe that running the deploy to an existing stack would update the runtime, otherwise we would still have nodejs12.x lambdas running in all the APIs that we've upgrade to nodejs16.x

The only other thing that has changed is the index.js file which just handles the command line and not the AWS infrastructure.

As for testing, I've run the performance test with an updated version of bom-artillery using a beta version of this package deployed from this branch (e.g. api-warnings -> bom-artillery@4.0.0-betaX -> bom-serverless-artillery@1.0.0-betaX)
The performance test passes for both the normal performance test and the notifications performance test - all metrics collected and validation looks good.

Pipeline run: https://jenkins.cicd.service.bom.gov.au/blue/organizations/jenkins/AusBOM%2Fapi-warnings/detail/feature-sls3/21/pipeline/64

**Comment by nylemat** [comment]
> > @Plitzer, first of all, thank you very much for addressing this issue.
> > My only thought is to run a couple of rounds of tests before we roll it out. We should make sure that existing cloud formation stack is removed before we run the test or else it would use the old infrastructure
> > @Plitzer, let me know, I can help you with testing
> 
> Thanks @nylemat The infrastructure should remain the same, only that the lambda runtime should be running nodejs16.x. I believe that running the deploy to an existing stack would update the runtime, otherwise we would still have nodejs12.x lambdas running in all the APIs that we've upgrade to nodejs16.x
> 
> The only other thing that has changed is the index.js file which just handles the command line and not the AWS infrastructure.
> 
> As for testing, I've run the performance test with an updated version of bom-artillery using a beta version of this package deployed from this branch (e.g. api-warnings -> [bom-artillery@4.0.0-betaX](mailto:bom-artillery@4.0.0-betaX) -> [bom-serverless-artillery@1.0.0-betaX](mailto:bom-serverless-artillery@1.0.0-betaX)) The performance test passes for both the normal performance test and the notifications performance test - all metrics collected and validation looks good.
> 
> Pipeline run: https://jenkins.cicd.service.bom.gov.au/blue/organizations/jenkins/AusBOM%2Fapi-warnings/detail/feature-sls3/21/pipeline/64

LGTM

**Review by nylemat — APPROVED** [review]

**Pull request merged**
